### ISSUE TITLE
Why not use USB CDC ?

### ISSUE THREAD

**Issue by x893** [ObdDiag-Net/elm329#1]
Hi,
good project. Thanks
Only 2 questions
1. Why not use internal USB CDC implementation ?
2. Why use C++ ?

Thanks in advance

**Comment by ObdDiag-Net** [comment]
The idea was to provide the open-source implementation of OBDII stack. Using SMT32F042 CDC driver is trivial when the most folks are interested is to connecting the adapter to Bluetooth BLE or WiFi module. In this case the serial protocol is preferable, see the original web page http://www.obddiag.net/elm329.html
Regards, Alex
